"""OrchidRec: reproducible recommendation experiments and benchmarks."""

from orchidrec.benchmark import (
    BenchmarkResult,
    BenchmarkTuningResult,
    ModelTuningResult,
    TuningCandidateResult,
    TuningTrial,
    run_benchmark,
)
from orchidrec.benchmark_config import (
    BenchmarkConfig,
    BenchmarkDataConfig,
    BenchmarkEvaluationConfig,
    BenchmarkModelSpec,
    BenchmarkSplitConfig,
    BenchmarkTuningConfig,
    BenchmarkValidationSplitConfig,
    benchmark_config_from_dict,
    load_benchmark_config,
    save_benchmark_config,
)
from orchidrec.config import ExperimentConfig, load_config
from orchidrec.data import EntityId, Interaction, InteractionDataset, StableIdMap
from orchidrec.datasets import (
    DatasetFormat,
    DatasetSummary,
    LoadedDataset,
    interaction_fingerprint,
    load_dataset,
    load_movielens,
)
from orchidrec.experiment import ExperimentResult, run_experiment
from orchidrec.features import (
    PAD_INDEX,
    UNKNOWN_INDEX,
    EncodedFeatureDataset,
    EncodedFeatureRow,
    FeatureDataset,
    FeatureKind,
    FeatureLimits,
    FeatureRow,
    FeatureSchema,
    FeatureSource,
    FeatureSpec,
    FittedFeaturePipeline,
    NumericStatistics,
    SequenceKeep,
    feature_dataset_sha256,
    load_encoded_features,
    load_feature_dataset,
    save_encoded_features,
    save_feature_dataset,
)
from orchidrec.metrics import MetricReport, evaluate_ranking
from orchidrec.models import (
    EASE,
    ConfidenceALS,
    ImplicitMF,
    ItemKNN,
    Popularity,
    Recommendation,
    SequentialMarkov,
    UserKNN,
)
from orchidrec.propensity import (
    DEFAULT_EXPONENT,
    DEFAULT_MINIMUM_PROPENSITY,
    ExposureModel,
    popularity_exposure,
    uniform_exposure,
)
from orchidrec.recbole_knowledge import (
    AtomicSource,
    CatalogReference,
    ItemEntityLink,
    KnowledgeLimits,
    KnowledgeTriple,
    LoadedKnowledgeLinks,
    import_recbole_knowledge,
    load_recbole_knowledge,
    save_recbole_knowledge,
)
from orchidrec.recbole_side import (
    LoadedRecBoleSideFeatures,
    RecBoleSideLimits,
    import_recbole_side_features,
    load_recbole_side_features,
    save_recbole_side_features,
)
from orchidrec.reporting import BenchmarkReportPaths, save_benchmark_reports
from orchidrec.sampling import (
    SAMPLER_REGISTRY,
    CandidatePlan,
    SamplingConfig,
    sample_candidates,
)
from orchidrec.split import SplitResult, leave_one_out, random_split, temporal_split
from orchidrec.statistics import (
    BootstrapInterval,
    PairedBootstrapResult,
    bootstrap_mean,
    interval_from_draws,
    paired_bootstrap_mean,
    paired_comparison_from_draws,
)
from orchidrec.unbiased import (
    UnbiasedMetricReport,
    evaluate_unbiased_ranking,
    ips_ndcg_at_k,
    ips_recall_at_k,
)

__all__ = [
    "DEFAULT_EXPONENT",
    "DEFAULT_MINIMUM_PROPENSITY",
    "EASE",
    "PAD_INDEX",
    "SAMPLER_REGISTRY",
    "UNKNOWN_INDEX",
    "AtomicSource",
    "BenchmarkConfig",
    "BenchmarkDataConfig",
    "BenchmarkEvaluationConfig",
    "BenchmarkModelSpec",
    "BenchmarkReportPaths",
    "BenchmarkResult",
    "BenchmarkSplitConfig",
    "BenchmarkTuningConfig",
    "BenchmarkTuningResult",
    "BenchmarkValidationSplitConfig",
    "BootstrapInterval",
    "CandidatePlan",
    "CatalogReference",
    "ConfidenceALS",
    "DatasetFormat",
    "DatasetSummary",
    "EncodedFeatureDataset",
    "EncodedFeatureRow",
    "EntityId",
    "ExperimentConfig",
    "ExperimentResult",
    "ExposureModel",
    "FeatureDataset",
    "FeatureKind",
    "FeatureLimits",
    "FeatureRow",
    "FeatureSchema",
    "FeatureSource",
    "FeatureSpec",
    "FittedFeaturePipeline",
    "ImplicitMF",
    "Interaction",
    "InteractionDataset",
    "ItemEntityLink",
    "ItemKNN",
    "KnowledgeLimits",
    "KnowledgeTriple",
    "LoadedDataset",
    "LoadedKnowledgeLinks",
    "LoadedRecBoleSideFeatures",
    "MetricReport",
    "ModelTuningResult",
    "NumericStatistics",
    "PairedBootstrapResult",
    "Popularity",
    "RecBoleSideLimits",
    "Recommendation",
    "SamplingConfig",
    "SequenceKeep",
    "SequentialMarkov",
    "SplitResult",
    "StableIdMap",
    "TuningCandidateResult",
    "TuningTrial",
    "UnbiasedMetricReport",
    "UserKNN",
    "benchmark_config_from_dict",
    "bootstrap_mean",
    "evaluate_ranking",
    "evaluate_unbiased_ranking",
    "feature_dataset_sha256",
    "import_recbole_knowledge",
    "import_recbole_side_features",
    "interaction_fingerprint",
    "interval_from_draws",
    "ips_ndcg_at_k",
    "ips_recall_at_k",
    "leave_one_out",
    "load_benchmark_config",
    "load_config",
    "load_dataset",
    "load_encoded_features",
    "load_feature_dataset",
    "load_movielens",
    "load_recbole_knowledge",
    "load_recbole_side_features",
    "paired_bootstrap_mean",
    "paired_comparison_from_draws",
    "popularity_exposure",
    "random_split",
    "run_benchmark",
    "run_experiment",
    "sample_candidates",
    "save_benchmark_config",
    "save_benchmark_reports",
    "save_encoded_features",
    "save_feature_dataset",
    "save_recbole_knowledge",
    "save_recbole_side_features",
    "temporal_split",
    "uniform_exposure",
]

__version__ = "0.11.0"
